# Dataset Creation

Experiment: Instead of having feature of horse's father and mother encoded, Create features containing their

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from dataHandler import *

In [3]:
df = pd.read_csv('data/horseData.csv')
df.head()

/var/folders/m6/wqgw_v5x3tq4t4q1zm2fc5f80000gn/T/ipykernel_4325/1900553122.py:1: DtypeWarning: Columns (17,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/horseData.csv')

,name,form,rating,rawErg,erg,ems,grade,yob,sex,sire,...,ems3,grade4,bmSire,price,status,code,lot,vendor,purchaser,prev. price
0,America's Joy,UR,0,69,72,0,0,2018,F,American Pharoah,...,61,C1,Tricky Creek,8200000,Sold,KESEP,498.0,"Clarkland Farm, LLC","Whisper Hill Farm, Llc",NaN
1,Aussie Pride,W,86,80,71,0,0,2018,G,Curlin,...,57,C1,Lonhro,4100000,Sold,KESEP,274.0,"Eaton Sales, Agent for Stonestreet Bred & Raised",Godolphin,NaN
2,Lady Take Charge,UR,0,134,108,0,0,2015,F,War Front,...,68,C1,Dehere,3200000,Sold,KENOV,451.0,Eaton Sales,Whisper Hill Farm,NaN
3,Mendelssohn,G1w,101,73,73,0,0,2015,C,Scat Daddy,...,56,C1,Tricky Creek,3000000,Sold,KESEP,454.0,Clarkland Farm,M.V. Magnier,NaN
4,Serena's Harmony,UR,0,113,118,0,0,2014,F,Tapit,...,66,C1,Storm Cat,3000000,Sold,KENOV,402.0,Hill 'n' Dale Sales Agency,Bridlewood Farm,NaN

In [4]:
df = clean_data(df)
df.head()

Shape of dataset: (65150, 24)

,name,form,rating,rawErg,erg,age,sire,fee,crop,dam,ems3,bmSire,damForm,sex_C,sex_F,sex_G,sex_R
1,Aussie Pride,2,86,80,71,8,Curlin,150000.0,9,Bounding,57,Lonhro,4,0.0,0.0,1.0,0.0
3,Mendelssohn,4,101,73,73,11,Scat Daddy,30000.0,7,Leslie's Lady,56,Tricky Creek,0,1.0,0.0,0.0,0.0
5,Brother in Arms,1,79,90,91,8,War Front,250000.0,11,Believe You Can,57,Proud Citizen,4,0.0,0.0,1.0,0.0
7,Gun It,2,97,150,150,10,Tapit,300000.0,11,Miss Besilu,79,Medaglia d'Oro,3,1.0,0.0,0.0,0.0
8,Declarationofpeace,0,85,127,118,11,War Front,150000.0,8,Serena's Cat,67,Storm Cat,0,1.0,0.0,0.0,0.0

Getting the form, rating, rawERg from the father and mother horse
- Can also add the parent's erg as well

In [5]:
df['avgSireRating'] = (df.groupby('sire')['rating'].transform('mean'))
df['avgSireErg'] = (df.groupby('sire')['erg'].transform('mean'))
df['avgSireForm'] = (df.groupby('sire')['form'].transform('mean'))

df['avgDamRating'] = (df.groupby('dam')['rating'].transform('mean'))
df['avgDamErg'] = (df.groupby('dam')['erg'].transform('mean'))

df['avgBmSireRating'] = (df.groupby('bmSire')['rating'].transform('mean'))
df['avgBmSireErg'] = (df.groupby('bmSire')['erg'].transform('mean'))
df['avgBmSireForm'] = (df.groupby('bmSire')['form'].transform('mean'))

df.to_csv('data/encodedHorseData.csv')

In [6]:
df.columns

Index(['name', 'form', 'rating', 'rawErg', 'erg', 'age', 'sire', 'fee', 'crop',
       'dam', 'ems3', 'bmSire', 'damForm', 'sex_C', 'sex_F', 'sex_G', 'sex_R',
       'avgSireRating', 'avgSireErg', 'avgSireForm', 'avgDamRating',
       'avgDamErg', 'avgBmSireRating', 'avgBmSireErg', 'avgBmSireForm'],
      dtype='object')